name: axonserver-connector-java-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: axonserver-connector-java
      repo-url: https://github.com/AxonIQ/axonserver-connector-java
      coordinates: io.axoniq:axonserver-connector-java
    secrets: inherit
