name: azure-security-keyvault-keys

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: ./.github/workflows/update-azure-sdk-mapping.yml
    with:
      mapping-name: azure-security-keyvault-keys
      skip-on-error: true
    secrets: inherit