name: azure-core-http-netty-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: ./.github/workflows/update-azure-sdk-mapping.yml
    with:
      mapping-name: azure-core-http-netty
      module-path: 'sdk/core/azure-core-http-netty'
      skip-on-error: true
      min-version: 1.5
    secrets: inherit