name: azure-sdk-azure-identity Mapping Workflow

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: ./.github/workflows/reusable-mapping.yml
    with:
      mapping-name: azure-sdk-azure-identity
      github-url: https://github.com/rabeyta/azure-sdk-for-java
        coordinates: com.azure:azure-identity
      secrets: inherit
