name: camel-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs at 9:00 AM UTC on the 1st and 15th of every month
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write
  
jobs:
  call-mapping-workflow:
    uses: rabeyta/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: camel-spring-main
      repo-url: "https://github.com/apache/camel"
      coordinates: "org.apache.camel:camel-spring-main"
    secrets: inherit