name: cucumber-jvm-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [cucumber-jvm]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/create-mapping.yml@main
    with:
      mapping-name: cucumber-jvm
      repo-url: https://github.com/cucumber/cucumber-jvm
      before-mapping-script: scripts/mapping-prepare/cucumber-jvm.py
    secrets: inherit
