name: dubbo-spring-boot-autoconfigure-compatible-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [dubbo-spring-boot-autoconfigure-compatible]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: dubbo-spring-boot-autoconfigure-compatible
      repo-url: https://github.com/apache/dubbo/dubbo-spring-boot-project/dubbo-spring-boot-compatible/dubbo-spring-boot-autoconfigure-compatible
      coordinates: org.apache.dubbo:dubbo-spring-boot-autoconfigure-compatible
    secrets: inherit
