name: graphql-kickstart-spring-webflux-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: graphql-kickstart-spring-webflux
      repo-url: https://github.com/graphql-java-kickstart/graphql-spring-boot
      coordinates: com.graphql-java-kickstart:graphql-kickstart-spring-webflux
    secrets: inherit
