name: graphql-java-kickstart-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [graphql-java-kickstart]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: graphql-java-kickstart
      repo-url: https://github.com/graphql-java-kickstart/graphql-java-servlet
      coordinates: com.graphql-java-kickstart:graphql-java-kickstart
    secrets: inherit
