name: hive-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs at 9:00 AM UTC on the 1st and 15th of every month
    - cron: '0 7 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: hive
      repo-url: "https://github.com/apache/hive"
    secrets: inherit