name: jazzer-junit-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [jazzer-junit]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/create-mapping.yml@main
    with:
      mapping-name: jazzer-junit
      repo-url: https://github.com/CodeIntelligenceTesting/jazzer
      coordinates: com.code-intelligence:jazzer-junit
      after-mapping-script: scripts/mapping-cleanup/jazzer-junit.py
    secrets: inherit
