name: micrometer-custom-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [micrometer-custom]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: micrometer-custom
      repo-url: https://github.com/micrometer-metrics/micrometer
      coordinates: io.micrometer:micrometer-core
    secrets: inherit
