name: shedlock-sql-support-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [shedlock-sql-support]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/create-mapping.yml@main
    with:
      mapping-name: shedlock-sql-support
      repo-url: https://github.com/lukas-krecan/ShedLock
      coordinates: net.javacrumbs.shedlock:shedlock-sql-support
      after-mapping-script: scripts/mapping-cleanup/shedlock-sql-support.py
    secrets: inherit
