name: shedlock-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs at 9:00 AM UTC on the 1st and 15th of every month
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: shedlock
      repo-url: "https://github.com/lukas-krecan/ShedLock"
      coordinates: "net.javacrumbs.shedlock:shedlock-spring"
    secrets: inherit