name: spring-boot-session-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [spring-boot-session]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/create-mapping.yml@main
    with:
      mapping-name: spring-boot-session
      repo-url: https://github.com/spring-projects/spring-boot
      coordinates: org.springframework.boot:spring-boot-session
      after-mapping-script: scripts/mapping-cleanup/spring-boot-session.py
    secrets: inherit
