name: togglz-spring-boot-starter-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: togglz-spring-boot-starter
      repo-url: https://github.com/togglz/togglz
      coordinates: org.togglz:togglz-spring-boot-starter
    secrets: inherit